"""Add confidence to meter_readings

Revision ID: bcda19a4a70e
Revises: 039efe43bd8b
Create Date: 2026-07-20 19:20:47.197357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcda19a4a70e'
down_revision: Union[str, Sequence[str], None] = '039efe43bd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('confidence', sa.Float(), nullable=True))
    op.drop_column('meter_readings', 'unit')
    op.drop_column('meter_readings', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('meter_readings', sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('meter_readings', 'confidence')
    # ### end Alembic commands ###
