"""rename column to min_conf

Revision ID: bd12d9e991df
Revises: bcda19a4a70e
Create Date: 2026-07-21 10:19:34.259798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd12d9e991df'
down_revision: Union[str, Sequence[str], None] = 'bcda19a4a70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('min_conf', sa.Float(), nullable=True))
    op.drop_column('meter_readings', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('meter_readings', 'min_conf')
    # ### end Alembic commands ###
