"""
Small structural interfaces. Concrete implementations live in adapters/ and infra/.
Using Protocol so tests can pass plain classes without inheriting anything.
"""
from __future__ import annotations

from typing import Optional, Protocol, Sequence

from app.domain.models import Detection, Frame


class KeyValueStore(Protocol):
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str, ttl: Optional[int] = None) -> bool: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def seconds_since(self, key: str) -> Optional[float]: ...
    def set_timestamp(self, key: str, ttl: Optional[int] = None) -> float: ...


class Notifier(Protocol):
    def send_message(self, message: str, parse_mode: str = "Markdown") -> bool: ...
    def send_alert(self, alert_type: str, data: Optional[dict] = None) -> bool: ...


class ActivityRepository(Protocol):
    def log_person_detected(self, person_data: dict) -> None: ...
    def log_person_left(self, person_data: dict) -> None: ...


class Detector(Protocol):
    def detect(self, frame: Frame) -> Sequence[Detection]: ...


class FrameSource(Protocol):
    def read(self) -> Optional[Frame]: ...
    def release(self) -> None: ...
    @property
    def fps(self) -> float: ...
