"""
Small structural interfaces. Concrete implementations live in adapters/ and infra/.
Using Protocol so tests can pass plain classes without inheriting anything.
"""
from __future__ import annotations

from enum import Enum
from typing import Protocol, Sequence

from app.domain.models import Detection, Frame

class AlertType(str, Enum):
    STARTUP = "startup"
    GAS_ALERT = "gas_alert"

class KeyValueStore(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str, ttl: int | None = None) -> bool: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def seconds_since(self, key: str) -> float | None: ...
    def set_timestamp(self, key: str, ttl: int | None = None) -> float: ...


class Notifier(Protocol):
    def send_message(self, message: str, parse_mode: str = "Markdown") -> bool: ...
    def send_alert(self, alert_type: AlertType, data: dict | None = None) -> bool: ...


class ActivityRepository(Protocol):
    def log_person_detected(self, person_data: dict) -> None: ...
    def log_person_left(self, person_data: dict) -> None: ...


class Detector(Protocol):
    def detect(self, frame: Frame) -> Sequence[Detection]: ...


class FrameSource(Protocol):
    def read(self) -> Frame | None: ...
    def release(self) -> None: ...
    @property
    def fps(self) -> float: ...