events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html/browser;
        index index.html;

        # Angular routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to backend container
        location /api/ {
            # Use service name from docker-compose
            proxy_pass http://cnn-recognizer:5002/;  # 'backend' is the service name
            # proxy_pass http://backend:5001/;  # 'backend' is the service name
            # proxy_pass http://192.168.0.254:5001/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Important for FastAPI
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}